### ISSUE TITLE
pkg_resources.DistributionNotFound: colorama

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/gcloud-python-expenses-demo#5]
Tried running the example code, and got this error:

C:\Users\shout-app-903\code\gcloud-python-expenses-demo-master>submit_expenses c
reate --employee-id=sally --description="Frotz project kickoff, San Jose" expens
es.csv
Traceback (most recent call last):
  File "C:\Python27\Scripts\submit_expenses-script.py", line 5, in <module>
    from pkg_resources import load_entry_point
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 2880, in <module>
    working_set = WorkingSet._build_master()
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 432, in _build_mas
ter
    ws.require(__requires__)
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 741, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: colorama

**Comment by tseaver** [comment]
Although I'm pretty sure this project has lagged behind the latest release of https://github.com/GoogleCloudPlatform/gcloud-python , that error is puzzling:  `colorama` is not needed or used by it or by any of its dependencies.

How did you install it?

**Comment by SurferJeffAtGoogle** [comment]
Is there a demo project that hasn't lagged behind the latest release?  Is
there another demo project I should be looking at?

**Comment by tseaver** [comment]
I just updated this one this morning:  it works for me with the master.

I still don't see how the errors I fixed today could have provoked the error you reported, though.

**Comment by SurferJeffAtGoogle** [comment]
What kind of google compute instance (OS version and hardware) did you test
it on?

**Comment by dhermes** [comment]
Let's flip this around. What commands did you run to get this error.

`colorama` has absolutely nothing to do with this sample or the library

**Comment by tseaver** [comment]
I cannot reproduce with a [virtualenv built on my own machine](https://gist.github.com/tseaver/69eed65fdb43c941184f).

**Comment by SurferJeffAtGoogle** [comment]
This happened on my Windows 2012 machine.

**Comment by dhermes** [comment]
Yeah the `C:` at the beginning of the path makes that much clear.

What commands did you run to get the error? How did you setup your environment?

**Comment by SurferJeffAtGoogle** [comment]
I installed Python 2.7.9.

Then:
pip install gcloud

Then I downloaded and unpacked the .zip.

Then:
$ cd /path/to/gcloud-python-expenses-demo
$ /path/to/virtualenv/bin/pip install -e .

Then I set GCLOUD_TESTS_* environment variables.

Then, I ran the submit_expenses command.

**Comment by tseaver** [comment]
I just saw a "needs colorama" bit in an [entirely unrelated project](https://github.com/zopefoundation/zopetoolkit/pull/11/files).  I wonder if it is now a dependcy of setuptools?
